// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show JsonMapper, JsonMapperAdapter, typeOf;
import 'input_mapping.dart' as x0 show InputProperties;
// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:moon/serialization/input_mapping.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'InputProperties',
            r'.InputProperties',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2],
            const <int>[3, 4, 5, 6, 7, 0, 1],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (_properties) =>
                  b ? prefix1.InputProperties(_properties) : null
            },
            -1,
            0,
            const <int>[],
            const [prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(
            r'unmappedSet',
            262146,
            0,
            -1,
            1,
            1,
            const <int>[],
            const <int>[0, 1],
            const prefix0.JsonSerializable(),
            const [prefix0.jsonProperty]),
        r.MethodMirrorImpl(
            r'unmappedGet',
            4325378,
            0,
            -1,
            2,
            3,
            null,
            const <int>[],
            const prefix0.JsonSerializable(),
            const [prefix0.jsonProperty]),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[], const <int>[2],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 4, 4, const <int>[],
            const <int>[3], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'name',
            32774,
            0,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            16390,
            0,
            const prefix0.JsonSerializable(),
            -1,
            -1,
            -1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_properties',
            2130982,
            2,
            const prefix0.JsonSerializable(),
            -1,
            2,
            3,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            3,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            5,
            const prefix0.JsonSerializable(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.InputProperties,
        const m.TypeValue<void>().type,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        bool,
        String,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'unmappedSet': (dynamic instance) => instance.unmappedSet,
        r'unmappedGet': (dynamic instance) => instance.unmappedGet
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void _initializeReflectable(JsonMapperAdapter adapter) {
  if (!adapter.isGenerated) {
    return;
  }
  r.data = adapter.reflectableData!;
  r.memberSymbolMap = adapter.memberSymbolMap;
}

final mainGeneratedAdapter = JsonMapperAdapter(
    title: 'Main Generated Adapter',
    url: 'package:moon/main.dart',
    reflectableData: _data,
    memberSymbolMap: _memberSymbolMap,
    valueDecorators: {
      typeOf<List<x0.InputProperties>>(): (value) =>
          value.cast<x0.InputProperties>(),
      typeOf<Set<x0.InputProperties>>(): (value) =>
          value.cast<x0.InputProperties>()
    },
    enumValues: {});

Future<JsonMapper> initializeJsonMapperAsync(
        {Iterable<JsonMapperAdapter> adapters = const []}) =>
    Future(() => initializeJsonMapper(adapters: adapters));

JsonMapper initializeJsonMapper(
    {Iterable<JsonMapperAdapter> adapters = const []}) {
  JsonMapper.enumerateAdapters([...adapters, mainGeneratedAdapter],
      (JsonMapperAdapter adapter) {
    _initializeReflectable(adapter);
    JsonMapper().useAdapter(adapter);
  });
  return JsonMapper();
}
